<?php

namespace Yusuke\SnapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends EntityRepository
{
    public function selectModels($limit)
    {
        $models = $this->findBy(array('deleteFlag' => 0), array('id' => 'DESC'), $limit);
        return $models;
    }
}
